import type { UserProfile, DailyHabits, Recommendations, LifeImpact } from '../types';

// @ts-ignore
const { jsPDF } = window.jspdf;

// --- PDF Generation Service ---

// Constants for PDF layout and styling
const MARGIN = 15;
const DOC_WIDTH = 210; // A4 width in mm
const USABLE_WIDTH = DOC_WIDTH - 2 * MARGIN;
const DOC_HEIGHT = 297; // A4 height in mm

const FONT_SIZES = {
  title: 22,
  h1: 16,
  h2: 12,
  body: 10,
  small: 8,
};

const COLORS = {
  primary: '#4338CA', // indigo-700
  secondary: '#059669', // green-600
  danger: '#DC2626', // red-600
  text: '#1F2937', // gray-800
  lightText: '#6B7281', // gray-500
  yellow: '#F59E0B', // yellow-500
};

const LINE_SPACING = 5;

let pdf: any;
let currentY = 0;

/**
 * Resets font to default body style.
 */
function resetFont() {
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(FONT_SIZES.body);
    pdf.setTextColor(COLORS.text);
}

/**
 * Checks if a new page is needed and adds it, including footer and header reset.
 * @param yOffset The height of the content to be added.
 */
function checkPageBreak(yOffset = 0) {
  if (currentY + yOffset > DOC_HEIGHT - 25) {
    pdf.addPage();
    currentY = MARGIN + 10;
  }
}

/**
 * Draws the main header for the report.
 */
function drawHeader() {
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(FONT_SIZES.title);
  pdf.setTextColor(COLORS.primary);
  pdf.text('AI Health Report', MARGIN, 20);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(FONT_SIZES.body);
  pdf.setTextColor(COLORS.lightText);
  pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, MARGIN, 28);
  
  currentY = 40;
}

/**
 * Draws the footer on the current page.
 */
function drawFooter(pageNum: number, pageCount: number) {
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.setFont('helvetica', 'italic');
    pdf.setFontSize(FONT_SIZES.small);
    pdf.setTextColor(COLORS.lightText);
    const footerText1 = 'This report is generated by an AI assistant and is for informational purposes only.';
    const footerText2 = 'It is not a substitute for professional medical advice. Always seek the advice of your physician.';
    pdf.line(MARGIN, pageHeight - 20, DOC_WIDTH - MARGIN, pageHeight - 20);
    pdf.text(footerText1, MARGIN, pageHeight - 15);
    pdf.text(footerText2, MARGIN, pageHeight - 10);
    pdf.text(`Page ${pageNum} of ${pageCount}`, DOC_WIDTH - MARGIN - 20, pageHeight - 10);
}

/**
 * Draws a styled section title with a line underneath.
 * @param title The title of the section.
 */
function drawSectionTitle(title: string) {
    checkPageBreak(20);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(FONT_SIZES.h1);
    pdf.setTextColor(COLORS.text);
    pdf.text(title, MARGIN, currentY);
    currentY += 3;
    pdf.setDrawColor(COLORS.text);
    pdf.setLineWidth(0.5);
    pdf.line(MARGIN, currentY, DOC_WIDTH - MARGIN, currentY);
    currentY += 8;
}

/**
 * A robust function to draw wrapped text line by line.
 * @param text The text to wrap and draw.
 * @param x The starting x-coordinate.
 * @param maxWidth The maximum width for the text lines.
 * @returns The new y-coordinate after drawing.
 */
function drawWrappedText(text: string, x: number, maxWidth: number): number {
    if (!text) return currentY;
    const lines = pdf.splitTextToSize(text, maxWidth);
    checkPageBreak(lines.length * LINE_SPACING);
    lines.forEach((line: string) => {
        pdf.text(line, x, currentY);
        currentY += LINE_SPACING;
    });
    return currentY;
}

/**
 * Draws a list of factors in a two-column layout.
 */
function drawFactorColumns(riskFactors: LifeImpact['riskFactors'], positiveFactors: LifeImpact['positiveFactors']) {
    const colWidth = (USABLE_WIDTH / 2) - 5;
    const col2X = MARGIN + colWidth + 10;
    
    // Draw Headers
    checkPageBreak(10);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(FONT_SIZES.h2);
    pdf.setTextColor(COLORS.danger);
    pdf.text('Key Risk Factors', MARGIN, currentY);
    pdf.setTextColor(COLORS.secondary);
    pdf.text('Key Positive Factors', col2X, currentY);
    currentY += 6;
    
    resetFont();

    let riskY = currentY;
    let positiveY = currentY;

    riskFactors.forEach(item => {
        const fullText = `• ${item.factor}: ${item.advice}`;
        const lines = pdf.splitTextToSize(fullText, colWidth);
        const requiredHeight = lines.length * LINE_SPACING + 2; // +2 for padding
        if (riskY + requiredHeight > DOC_HEIGHT - 25) {
            // This logic is simplified; a full implementation would move the other column as well
            // For now, we assume factors won't break pages mid-list often
            pdf.addPage();
            riskY = MARGIN + 10;
        }
        lines.forEach((line: string, index: number) => {
            if (index === 0) {
                const parts = line.split(':');
                const factor = parts[0] + ':';
                const advice = parts.slice(1).join(':');
                pdf.setFont('helvetica', 'bold');
                pdf.text(factor, MARGIN, riskY);
                const factorWidth = pdf.getTextWidth(factor);
                pdf.setFont('helvetica', 'normal');
                pdf.text(advice, MARGIN + factorWidth + 1, riskY);
            } else {
                pdf.text(line, MARGIN + 3, riskY); // Indent subsequent lines
            }
            riskY += LINE_SPACING;
        });
        riskY += 2; // Padding between items
    });

    positiveFactors.forEach(item => {
        const fullText = `• ${item.factor}: ${item.advice}`;
        const lines = pdf.splitTextToSize(fullText, colWidth);
        const requiredHeight = lines.length * LINE_SPACING + 2;
        if (positiveY + requiredHeight > DOC_HEIGHT - 25) {
             pdf.addPage();
             positiveY = MARGIN + 10;
        }
        lines.forEach((line: string, index: number) => {
             if (index === 0) {
                const parts = line.split(':');
                const factor = parts[0] + ':';
                const advice = parts.slice(1).join(':');
                pdf.setFont('helvetica', 'bold');
                pdf.text(factor, col2X, positiveY);
                const factorWidth = pdf.getTextWidth(factor);
                pdf.setFont('helvetica', 'normal');
                pdf.text(advice, col2X + factorWidth + 1, positiveY);
            } else {
                pdf.text(line, col2X + 3, positiveY); // Indent subsequent lines
            }
            positiveY += LINE_SPACING;
        });
        positiveY += 2; // Padding
    });

    currentY = Math.max(riskY, positiveY);
}

export const generateHealthReportPdf = (
    userProfile: UserProfile,
    habits: DailyHabits,
    recommendations: Recommendations,
    impact: LifeImpact
) => {
    pdf = new jsPDF('p', 'mm', 'a4');
    currentY = 0;

    drawHeader();

    // --- Profile Section ---
    drawSectionTitle('User Health Profile');
    resetFont();
    pdf.text(`Age: ${userProfile.age}`, MARGIN, currentY);
    pdf.text(`Gender: ${userProfile.gender}`, MARGIN + 70, currentY);
    currentY += 7;
    pdf.text(`Weight: ${userProfile.weight} kg`, MARGIN, currentY);
    pdf.text(`Height: ${userProfile.height} cm`, MARGIN + 70, currentY);
    currentY += 7;
    pdf.text(`Health Goal: ${userProfile.healthGoal.replace(/([A-Z])/g, ' $1').trim()}`, MARGIN, currentY);
    currentY += 7;
    pdf.text(`Medical Conditions: `, MARGIN, currentY);
    drawWrappedText(userProfile.conditions, MARGIN + 45, USABLE_WIDTH - 45);
    currentY += 5;

    // --- Life Impact Section ---
    drawSectionTitle('Life Impact Score & Analysis');
    const scoreYStart = currentY;
    pdf.setFontSize(FONT_SIZES.h2);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Your Score:', MARGIN, currentY);

    let scoreColor = COLORS.danger;
    if (impact.score > 75) scoreColor = COLORS.secondary;
    else if (impact.score > 50) scoreColor = COLORS.yellow;
    pdf.setTextColor(scoreColor);
    pdf.setFontSize(48);
    pdf.text(`${impact.score}`, MARGIN + 35, currentY + 7);
    resetFont();

    const summaryY = scoreYStart - 1; // Align top of summary with 'Your Score'
    const summaryLines = pdf.splitTextToSize(impact.summary, USABLE_WIDTH - 70);
    pdf.text(summaryLines, MARGIN + 75, summaryY);
    currentY += Math.max(30, summaryLines.length * LINE_SPACING + 5);
    
    drawFactorColumns(impact.riskFactors, impact.positiveFactors);
    currentY += 10;

    // --- Recommendations Section ---
    drawSectionTitle('Personalized Recommendations');
    
    // Diet
    checkPageBreak(15);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(FONT_SIZES.h2);
    pdf.setTextColor(COLORS.primary);
    pdf.text(`Diet Plan: ${recommendations.diet.planName}`, MARGIN, currentY);
    currentY += 6;
    pdf.setFont('helvetica', 'italic');
    pdf.setFontSize(FONT_SIZES.body);
    pdf.setTextColor(COLORS.lightText);
    drawWrappedText(recommendations.diet.description, MARGIN, USABLE_WIDTH);
    currentY += 4;
    resetFont();

    pdf.text(`Calories: ${recommendations.diet.dailyCalories} kcal`, MARGIN, currentY);
    pdf.text(`Protein: ${recommendations.diet.macronutrients.protein}`, MARGIN + USABLE_WIDTH / 2, currentY);
    currentY += 6;
    pdf.text(`Carbohydrates: ${recommendations.diet.macronutrients.carbohydrates}`, MARGIN, currentY);
    pdf.text(`Fats: ${recommendations.diet.macronutrients.fats}`, MARGIN + USABLE_WIDTH / 2, currentY);
    currentY += 8;
    
    pdf.setFont('helvetica', 'bold');
    pdf.text('Sample Meals:', MARGIN, currentY);
    currentY += 6;
    resetFont();
    
    const meals = [
      { label: 'Breakfast', text: recommendations.diet.sampleMeals.breakfast },
      { label: 'Lunch', text: recommendations.diet.sampleMeals.lunch },
      { label: 'Dinner', text: recommendations.diet.sampleMeals.dinner }
    ];
    
    meals.forEach(meal => {
        checkPageBreak(15);
        pdf.setFont('helvetica', 'bold');
        pdf.text(`${meal.label}:`, MARGIN + 2, currentY);
        resetFont();
        drawWrappedText(meal.text, MARGIN + 25, USABLE_WIDTH - 27);
        currentY += 2;
    });
    currentY += 8;
    
    // Workouts
    checkPageBreak(20);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(FONT_SIZES.h2);
    pdf.setTextColor(COLORS.secondary);
    pdf.text('Workout Routine', MARGIN, currentY);
    currentY += 6;
    resetFont();

    recommendations.workouts.forEach(workout => {
        checkPageBreak(15);
        pdf.setFont('helvetica', 'bold');
        const titleText = `• ${workout.type}`;
        pdf.text(titleText, MARGIN, currentY);
        resetFont();
        const details = `(${workout.frequency}, ${workout.duration})`;
        pdf.text(details, MARGIN + pdf.getTextWidth(titleText) + 2, currentY);
        currentY += 6;
        
        drawWrappedText(workout.description, MARGIN + 5, USABLE_WIDTH - 5);
        currentY += 4;
    });

    // --- Finalize and Save ---
    const pageCount = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        drawFooter(i, pageCount);
    }
    
    pdf.save(`AI_Health_Report_${new Date().toLocaleDateString().replace(/\//g, '-')}.pdf`);
};
